const state = { currentView: 'dashboard' };
const $ = (selector) => document.querySelector(selector);
const esc = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const flash = (message, isError = false) => { const element = $('#flash'); element.textContent = message; element.style.background = isError ? '#fff0df' : ''; element.style.color = isError ? '#a75c18' : ''; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 3500); };

function showView(view) {
  state.currentView = view;
  document.querySelectorAll('.view').forEach((element) => element.classList.toggle('active-view', element.id === `${view}-view`));
  document.querySelectorAll('.nav-item').forEach((element) => element.classList.toggle('active', element.dataset.view === view));
  const labels = { dashboard: ['Overview', 'Chain of custody, at a glance.'], sites: ['Construction sites', 'Every origin, accounted for.'], vehicles: ['Vehicles', 'A reusable fleet with a permanent history.'], transport: ['Transport monitor', 'Follow every load to its authorized destination.'], tracking: ['GPS tracking', 'Manual simulation, device-ready by design.'] };
  $('#view-label').textContent = labels[view][0]; $('#page-title').textContent = labels[view][1];
  if (view === 'dashboard') loadOverview();
  if (view === 'sites') loadSites();
  if (view === 'vehicles') loadVehicles();
  if (view === 'transport') loadTransports();
  if (view === 'tracking') loadGps();
}

function statusTag(status) { return `<span class="status-tag ${status === 'Mismatch' ? 'warning' : ''}">${esc(status || 'Pending')}</span>`; }
function emptyRow(message, columns) { return `<tr><td colspan="${columns}" style="color:var(--muted)">${esc(message)}</td></tr>`; }

async function loadOverview() {
  try {
    const [healthResponse, data] = await Promise.all([fetch('/health'), dashboard.load()]);
    $('#health-status').textContent = healthResponse.ok ? 'API online' : 'API unavailable';
    const cards = [['total_sites', 'Total sites'], ['active_sites', 'Active sites'], ['total_vehicles', 'Vehicles'], ['active_transports', 'Active transports'], ['weight_mismatches', 'Weight mismatches']];
    $('#stats-grid').innerHTML = cards.map(([key, label]) => `<article class="stat-card"><span>${label}</span><strong>${data[key] ?? 0}</strong></article>`).join('');
    $('#recent-transports').innerHTML = data.recent_transports?.length ? data.recent_transports.map((item) => `<tr><td>${esc(item.transport_id)}</td><td>${esc(item.site_id)} -> ${esc(item.facility_id)}</td><td>${esc(item.waste_type || item.waste_id)}</td><td>${statusTag(item.status)}</td><td>${item.loaded_weight_kg ?? '-'} kg</td></tr>`).join('') : emptyRow('No transport records yet.', 5);
    $('#verification-alerts').innerHTML = data.weight_mismatches ? `<div class="alert-item"><strong>${data.weight_mismatches}</strong> load${data.weight_mismatches === 1 ? '' : 's'} require review.</div>` : '<div class="alert-item" style="border-left-color:var(--green);background:#f1f7ee;color:var(--green)">No mismatches in the queue.</div>';
  } catch (error) { $('#health-status').textContent = 'MongoDB offline'; flash('Connect MongoDB to load live dashboard data.', true); }
}

async function loadSites() { try { const sites = await dashboard.sites(); $('#sites-table').innerHTML = sites.length ? sites.map((site) => `<tr><td>${esc(site.site_id)}</td><td><strong>${esc(site.name)}</strong></td><td>${esc(site.project_name || '-')}</td><td>${esc(site.address)}</td><td>${statusTag(site.status)}</td></tr>`).join('') : emptyRow('Create your first construction site.', 5); } catch (error) { $('#sites-table').innerHTML = emptyRow('Unable to load sites. Is MongoDB running?', 5); } }
async function loadVehicles() { try { const vehicles = await dashboard.vehicles(); $('#vehicles-table').innerHTML = vehicles.length ? vehicles.map((vehicle) => `<tr><td>${esc(vehicle.vehicle_id)}</td><td><strong>${esc(vehicle.registration_number)}</strong></td><td>${esc(vehicle.vehicle_type)}</td><td>${esc(vehicle.capacity_kg)} kg</td><td>${statusTag(vehicle.status)}</td><td><button class="text-button" data-history="${esc(vehicle.vehicle_id)}">View history</button></td></tr>`).join('') : emptyRow('Register your first vehicle.', 6); document.querySelectorAll('[data-history]').forEach((button) => button.addEventListener('click', () => showHistory(button.dataset.history))); } catch (error) { $('#vehicles-table').innerHTML = emptyRow('Unable to load vehicles. Is MongoDB running?', 6); } }
async function loadTransports() { try { const transports = await dashboard.transports(); $('#transport-table').innerHTML = transports.length ? transports.map((item) => `<tr><td><strong>${esc(item.transport_id)}</strong></td><td>${esc(item.site_id)}<br><small>${esc(item.facility_id)}</small></td><td>${esc(item.vehicle_id)}</td><td>${esc(item.waste_type || item.waste_id)}</td><td>${item.loaded_weight_kg ?? '-'} kg</td><td>${statusTag(item.status)}</td><td>${actionButton(item)}</td></tr>`).join('') : emptyRow('Create a transport to begin tracking chain of custody.', 7); bindTransportActions(); } catch (error) { $('#transport-table').innerHTML = emptyRow('Unable to load transports. Is MongoDB running?', 7); } }
function actionButton(item) { const actions = { Created: ['load', 'Enter load'], Loaded: ['start', 'Start trip'], 'In Transit': ['arrive', 'Mark arrived'], Arrived: ['verify', 'Verify weight'], Verified: ['complete', 'Complete'] }; const action = actions[item.status]; return action ? `<button class="text-button" data-action="${action[0]}" data-id="${esc(item.transport_id)}">${action[1]}</button>` : item.status === 'Mismatch' ? '<span style="color:#a75c18;font-size:11px">Review mismatch</span>' : '<span style="color:var(--muted);font-size:11px">Complete</span>'; }
function bindTransportActions() { document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => lifecycle(button.dataset.id, button.dataset.action))); }
async function lifecycle(id, action) { try { let data = {}; if (action === 'load') data = { weight_kg: Number(prompt('Loading weight (kg):')), source: 'manual' }; if (action === 'arrive') data = { received_weight_kg: Number(prompt('Receiving weight (kg):')), source: 'manual' }; if (action === 'load' || action === 'arrive') { if (!data[Object.keys(data)[0]]) return; } const result = action === 'load' || action === 'arrive' ? await api.post(`/transports/${id}/${action}`, data) : await api.post(`/transports/${id}/${action}`, {}); flash(result ? `Transport ${action} completed.` : 'Transport updated.'); loadTransports(); } catch (error) { flash(error.message, true); } }
async function loadGps() { try { const points = await dashboard.gps(); $('#gps-feed').innerHTML = points.length ? points.slice(0, 8).map((point) => `<div class="feed-item"><strong>${esc(point.transport_id)}</strong> at ${Number(point.latitude).toFixed(4)}, ${Number(point.longitude).toFixed(4)}<br><small>${esc(point.speed_kmph || 0)} km/h · ${esc(point.source)}</small></div>`).join('') : '<div class="feed-item">No GPS points recorded yet.</div>'; } catch (error) { $('#gps-feed').innerHTML = '<div class="feed-item">Unable to load GPS feed.</div>'; } }

function openModal(title, fields, submit) { $('#modal-content').innerHTML = `<p class="eyebrow">Manual entry</p><h2>${title}</h2><form id="modal-form" class="form-grid" style="padding:25px 0 0">${fields.map((field) => `<label>${field.label}<input name="${field.name}" type="${field.type || 'text'}" ${field.required === false ? '' : 'required'}></label>`).join('')}<button class="primary-button" type="submit">Create record</button></form>`; $('#modal').classList.add('open'); $('#modal').setAttribute('aria-hidden', 'false'); $('#modal-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.target); const data = Object.fromEntries(form.entries()); fields.filter((field) => field.type === 'number').forEach((field) => { if (data[field.name]) data[field.name] = Number(data[field.name]); }); try { await submit(data); $('#modal').classList.remove('open'); flash('Record created successfully.'); showView(state.currentView); } catch (error) { flash(error.message, true); } }); }
async function showHistory(vehicleId) { try { const records = await api.get(`/vehicles/${vehicleId}/history`); openModal(`${vehicleId} history`, [], async () => {}); $('#modal-content').innerHTML += `<div class="table-wrap" style="margin-top:20px"><table><thead><tr><th>Transport</th><th>Site</th><th>Facility</th><th>Status</th></tr></thead><tbody>${records.length ? records.map((item) => `<tr><td>${esc(item.transport_id)}</td><td>${esc(item.site_id)}</td><td>${esc(item.facility_id)}</td><td>${statusTag(item.status)}</td></tr>`).join('') : emptyRow('No historical trips.', 4)}</tbody></table></div>`; $('#modal-form')?.remove(); } catch (error) { flash(error.message, true); } }

document.querySelectorAll('.nav-item,[data-view]').forEach((button) => button.addEventListener('click', () => showView(button.dataset.view)));
$('#modal-close').addEventListener('click', () => $('#modal').classList.remove('open'));
$('#add-site').addEventListener('click', () => openModal('Add construction site', [{ name: 'name', label: 'Site name' }, { name: 'project_name', label: 'Project name' }, { name: 'address', label: 'Address' }], (data) => api.post('/sites', data)));
$('#add-vehicle').addEventListener('click', () => openModal('Register vehicle', [{ name: 'registration_number', label: 'Registration number' }, { name: 'vehicle_type', label: 'Vehicle type' }, { name: 'capacity_kg', label: 'Capacity (kg)', type: 'number' }], (data) => api.post('/vehicles', data)));
$('#add-transport').addEventListener('click', () => openModal('Create transport', [{ name: 'site_id', label: 'Site ID' }, { name: 'vehicle_id', label: 'Vehicle ID' }, { name: 'driver_id', label: 'Driver ID' }, { name: 'facility_id', label: 'Facility ID' }, { name: 'waste_id', label: 'Waste ID' }], (data) => api.post('/transports', data)));
$('#gps-form').addEventListener('submit', async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); data.latitude = Number(data.latitude); data.longitude = Number(data.longitude); data.speed_kmph = Number(data.speed_kmph); try { await api.post('/gps', data); flash('GPS point recorded.'); event.target.reset(); loadGps(); } catch (error) { flash(error.message, true); } });
showView(new URLSearchParams(location.search).get('view') || 'dashboard');
